### ISSUE TITLE
Change ip periodically

### ISSUE THREAD

**Issue by ikiraz18** [PeterDaveHello/tor-socks-proxy#10]
Hello, how can i change ip periodically ?

**Comment by PeterDaveHello** [comment]
@ikiraz18 It's 10 mins by default, you can override it by mounting your own torrc file.

**Comment by PeterDaveHello** [comment]
README.md updated: https://github.com/PeterDaveHello/tor-socks-proxy/commit/8f9077f0658775ab9441bcc643c0d14e9e3928a1
