### ISSUE TITLE
How can i edit torrc config file?

### ISSUE THREAD

**Issue by Jindey** [PeterDaveHello/tor-socks-proxy#14]

**Comment by PeterDaveHello** [comment]
@Jindey do you mean during the runtime? You can always use docker's volumes mount parameter `-v` to mount your own torrc file, see https://docs.docker.com/storage/volumes/ for more details! Thanks.

**Comment by PeterDaveHello** [comment]
Let me know if this should be also added to the README.md, if there are some users needed it, I'll reopen this issue.

**Comment by StephanGerbeth** [comment]
is this right? 

````
docker run -v $(pwd)/torrc:/torrc --name tor-socks-proxy -p 127.0.0.1:9150:9150/tcp -p 127.0.0.1:53:53/udp peterdavehello/tor-socks-proxy:latest
````
Currently it's not working. The file wont be copied to etc/tor. 
Can you help me?

**Comment by PeterDaveHello** [comment]
@StephanGerbeth torrc needs to be mounted to /etc/tor/ (See Dockerfile for the details)

**Comment by PeterDaveHello** [comment]
@StephanGerbeth You'll need to use -v $(pwd)/torrc:/etc/tor/torrc or -v $(pwd)/:/etc/tor/

**Comment by StephanGerbeth** [comment]
thanks!
