### ISSUE TITLE
Does it support DNS queries(.onion, .exit)?

### ISSUE THREAD

**Issue by just-a-b** [PeterDaveHello/tor-socks-proxy#15]
Hi,

Thank you in advance for providing this image.
I see that only 9150/tcp port is exposed in the dockerfile, so what about udp?

Best

**Comment by PeterDaveHello** [comment]
@just-a-b Tor does not use UDP at all, thanks.

**Comment by PeterDaveHello** [comment]
@just-a-b maybe I misunderstand your issue

@BokilaLin sent a PR #17 to enable DNS Port, maybe that's something you want?

If you need to resolve those `.onion` `.exit` domains, `AutomapHostsOnResolve` will also need to be added, but I'm not sure this is something really needed. Let me know what do you think, thanks.

**Comment by b1oki** [comment]
@PeterDaveHello `.onion` domains, like [DuckDuckGo](https://3g2upl4pq6kufc4m.onion/), works currently (connected to this docker service as SOCKS5 proxy).

**Comment by PeterDaveHello** [comment]
@b1oki if you directly use it as socks proxy, yes, there shouldn't be a problem.

**Comment by b1oki** [comment]
@just-a-b You want alternative for DNS over HTTPS and DNS over TLS? Cloudflare wrote about something like that: https://developers.cloudflare.com/1.1.1.1/fun-stuff/dns-over-tor/

**Comment by PeterDaveHello** [comment]
@b1oki I think it's not quite the same, especially if you want to resolve .onion or .exit, though I'm still not sure the scenario to resolve those domains outside tor network here, in the case tor is running inside a docker container.

**Comment by PeterDaveHello** [comment]
Close due to no response.
