### ISSUE TITLE
Healthcheck

### ISSUE THREAD

**Issue by ipepe** [PeterDaveHello/tor-socks-proxy#2]
What do You think about adding healthcheck?

```Dockerfile
HEALTHCHECK --interval=60s --timeout=15s --start-period=90s \
            CMD curl --socks5-hostname localhost:9050 -L 'https://api.ipify.org'
```

I copied it from https://github.com/dperson/torproxy/blob/master/Dockerfile

**Comment by PeterDaveHello** [comment]
Sounds great, wanna send a pull request 😄 ?
