### ISSUE TITLE
Open up to Local Network

### ISSUE THREAD

**Issue by darksky82** [PeterDaveHello/tor-socks-proxy#21]
Hi. How do I open it up so that all local IPs can access the proxy? Which parameter to use?
Thanks.

**Comment by PeterDaveHello** [comment]
@darksky82 Try to listen on the lan IP or eevn 0.0.0.0 instead of 127.0.0.1

**Comment by darksky82** [comment]
Thanks a lot for your response. Really much appreciated. 
Tor proxy has this configuration..
SocksPolicy accept 192.168.1.0/24 (or any other range)
Any way to set this? 

This is kind of very useful because in my case I want to run tor proxy in another box (other than the localhost) and use the box as a proxy for all systems in my net work. 

Any help will be very useful.

**Comment by PeterDaveHello** [comment]
@darksky82 You can mount your own torrc config into the container, or build your own image based on this one.
