### ISSUE TITLE
HTTPTunnelPort

### ISSUE THREAD

**Issue by Novemium** [PeterDaveHello/tor-socks-proxy#22]
Dear sir,

the abovementioned parameter/option doesn't seem to be working. Is it by design?
I really miss the opportunity to set up also an HTTP(S) proxy via tor.

Regards

**Comment by PeterDaveHello** [comment]
@Novemium HTTP(S) proxy is not directly supported by tor and this project itself, it's a SOCKS proxy,  you'll need to use proxy like privoxy to support HTTP proxy feature and forward to a SOCKS proxy.
