### ISSUE TITLE
running container throws exit code 1

### ISSUE THREAD

**Issue by realSConway** [PeterDaveHello/tor-socks-proxy#29]
Hi guys,
I was using the same container last week, and everyhting was working fine.
This week I migrate to new device, no longer able to run _tor-socks-proxy_, error code: _Exited (1) 1 second ago_

What am I forgetting?

When I run container, output as follows.
```
2021-09-09 15:37:55.292337884 +0000 UTC image pull  peterdavehello/tor-socks-proxy:latest
2021-09-09 15:37:55.6662729 +0000 UTC container create 2eda0ddd789146d8deca1c5e0b9a2adbfa267c67062f89d4d0e15009d276602a (image=docker.io/peterdavehello/tor-
socks-proxy:latest, name=tor-socks-proxy, version=latest, maintainer=Peter Dave Hello <hsu@peterdavehello.org>, name=tor-socks-proxy)
2eda0ddd789146d8deca1c5e0b9a2adbfa267c67062f89d4d0e15009d276602a
2021-09-09 15:37:56.99105287 +0000 UTC container init 2eda0ddd789146d8deca1c5e0b9a2adbfa267c67062f89d4d0e15009d276602a (image=docker.io/pe
terdavehello/tor-socks-proxy:latest, name=tor-socks-proxy, maintainer=Peter Dave Hello <hsu@peterdavehello.org>, name=tor-socks-proxy, version=latest)
2021-09-09 15:37:57.099668881 +0000 UTC container start 2eda0ddd789146d8deca1c5e0b9a2adbfa267c67062f89d4d0e15009d276602a (image=docker.io/peterdavehello/tor
-socks-proxy:latest, name=tor-socks-proxy, maintainer=Peter Dave Hello <hsu@peterdavehello.org>, name=tor-socks-proxy, version=latest)
2021-09-09 15:37:57.479898749 +0000 UTC container died 2eda0ddd789146d8deca1c5e0b9a2adbfa267c67062f89d4d0e15009d276602a (image=docker.io/peterdavehello/tor-
socks-proxy:latest, name=tor-socks-proxy)
```

**Output of `cat /etc/*release`:**
```
NAME="openSUSE MicroOS"
# VERSION="20210901"
ID="opensuse-microos"
ID_LIKE="suse opensuse opensuse-tumbleweed"
VERSION_ID="20210901"
PRETTY_NAME="openSUSE MicroOS"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:microos:20210901"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:MicroOS"
LOGO="distributor-logo"
```

**Output of `uname -a`:**
`Linux localhost 5.13.13-1-default #1 SMP Fri Aug 27 08:52:15 UTC 2021 (6339fac) aarch64 aarch64 aarch64 GNU/Linux`

**Output of `cat /etc/containers/storage.conf`:**
```
[storage]
driver = "btrfs"
runroot = "/var/run/containers/storage"
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = [
]
size = ""
ostree_repo = ""
[storage.options.thinpool]
```

Thanks in advance

**Comment by PeterDaveHello** [comment]
@realSConway Look like you're using arm-based machine?

**Comment by realSConway** [comment]
Correct, the device last week was also arm-based.

**Comment by PeterDaveHello** [comment]
@realSConway Arm is not directly supported here yet, but you can clone the repositoryand build locally!

**Comment by realSConway** [comment]
ok, thanks for the tip.
I'm using podman/buildah instead of docker. When attempting to build locally, another error/warning.
```
$ buildah build -f ./Dockerfile -t tor-socks-proxy
WARN[0000] Failed to decode the keys ["storage.options.ostree_repo"] from "/etc/containers/storage.conf".
unknown command "build" for "buildah"

Did you mean this?
        bud
```
No image is built.

**Comment by PeterDaveHello** [comment]
@realSConway What about using Docker official binary to build the image?

**Comment by realSConway** [comment]
Thanks for the help, I am able to build and run via docker... Any suggestions how I can try getting it to work with podman/buildah?

**Comment by PeterDaveHello** [comment]
@realSConway Sorry but I can only spend my limited spare time work on the most common use cases, so I have no suggestions here yet, if you found anything could be helpful, please feel free to send pull requests!

**Comment by realSConway** [comment]
No problem at all, thanks for everything.

If I find anything I will add. ;)

**Comment by realSConway** [comment]
Was able to run container after building from Dockerfile on raspberry pi.

1. `git clone https://github.com/PeterDaveHello/tor-socks-proxy.git`
2. `cd tor-socks-proxy`
3. `podman build -f ./Dockerfile`
