### ISSUE TITLE
Troubles with circuit establish in Russia

### ISSUE THREAD

**Issue by NickiHell** [PeterDaveHello/tor-socks-proxy#37]
Jun 27 08:23:43.718 [notice] Tor 0.4.7.7 running on Linux with Libevent 2.1.12-stable, OpenSSL 1.1.1n, Zlib 1.2.12, Liblzma 5.2.5, Libzstd 1.5.0 and Unknown N/A as libc.
Jun 27 08:23:43.718 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://support.torproject.org/faq/staying-anonymous/
Jun 27 08:23:43.718 [warn] Tor was compiled with zstd 1.5.2, but is running with zstd 1.5.0. For safety, we'll avoid using advanced zstd functionality.
Jun 27 08:23:43.718 [notice] Read configuration file "/etc/tor/torrc".
Jun 27 08:23:43.719 [warn] You specified a public address '0.0.0.0:8853' for DNSPort. Other people on the Internet might find your computer and use it as an open proxy. Please don't allow this unless you have a good reason.
Jun 27 08:23:43.720 [warn] You specified a public address '0.0.0.0:9150' for SocksPort. Other people on the Internet might find your computer and use it as an open proxy. Please don't allow this unless you have a good reason.
Jun 27 08:23:43.720 [warn] You specified a public address '0.0.0.0:8853' for DNSPort. Other people on the Internet might find your computer and use it as an open proxy. Please don't allow this unless you have a good reason.
Jun 27 08:23:43.720 [notice] Opening Socks listener on 0.0.0.0:9150
Jun 27 08:23:43.720 [notice] Opened Socks listener connection (ready) on 0.0.0.0:9150
Jun 27 08:23:43.720 [notice] Opening DNS listener on 0.0.0.0:8853
Jun 27 08:23:43.720 [notice] Opened DNS listener connection (ready) on 0.0.0.0:8853
Jun 27 08:23:43.000 [notice] Parsing GEOIP IPv4 file /usr/share/tor/geoip.
Jun 27 08:23:43.000 [notice] Parsing GEOIP IPv6 file /usr/share/tor/geoip6.
Jun 27 08:23:43.000 [notice] Bootstrapped 0% (starting): Starting
Jun 27 08:23:43.000 [notice] Starting with guard context "default"
Jun 27 08:23:44.000 [notice] Bootstrapped 5% (conn): Connecting to a relay
Jun 27 08:26:13.000 [notice] Tried for 120 seconds to get a connection to [scrubbed]:443. Giving up. (waiting for rendezvous desc)
Jun 27 08:26:53.000 [notice] Tried for 120 seconds to get a connection to [scrubbed]:443. Giving up. (waiting for rendezvous desc)
Jun 27 08:27:33.000 [notice] Tried for 120 seconds to get a connection to [scrubbed]:443. Giving up. (waiting for rendezvous desc)
Jun 27 08:28:13.000 [notice] Tried for 120 seconds to get a connection to [scrubbed]:443. Giving up. (waiting for rendezvous desc)
Jun 27 08:28:53.000 [notice] Tried for 120 seconds to get a connection to [scrubbed]:443. Giving up. (waiting for rendezvous desc)
Jun 27 08:29:33.000 [notice] Tried for 120 seconds to get a connection to [scrubbed]:443. Giving up. (waiting for rendezvous desc)
Jun 27 08:30:13.000 [notice] Tried for 120 seconds to get a connection to [scrubbed]:443. Giving up. (waiting for rendezvous desc)
Jun 27 08:30:53.000 [notice] Tried for 120 seconds to get a connection to [scrubbed]:443. Giving up. (waiting for rendezvous desc)
Jun 27 08:31:33.000 [notice] Tried for 120 seconds to get a connection to [scrubbed]:443. Giving up. (waiting for rendezvous desc)
Jun 27 08:31:53.000 [warn] Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Operation timed out; TIMEOUT; count 10; recommendation warn; host 7EA6EAD6FD83083C538F44038BBFA077587DD755 at 45.66.33.45:443)
Jun 27 08:31:53.000 [warn] 9 connections have failed:
Jun 27 08:31:53.000 [warn]  9 connections died in state connect()ing with SSL state (No SSL object)
Jun 27 08:31:53.000 [warn] Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Operation timed out; TIMEOUT; count 11; recommendation warn; host 6078F300B379D8DEBCF02DBE80881C94777E24BF at 198.255.21.2:443)
Jun 27 08:31:53.000 [warn] 10 connections have failed:
Jun 27 08:31:53.000 [warn]  10 connections died in state connect()ing with SSL state (No SSL object)
Jun 27 08:32:00.000 [warn] Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Operation timed out; TIMEOUT; count 12; recommendation warn; host C9B34ABF2C30DA56BD006B7B42610098072BEF4C at 54.93.77.70:9001)
Jun 27 08:32:00.000 [warn] 11 connections have failed:
Jun 27 08:32:00.000 [warn]  11 connections died in state connect()ing with SSL state (No SSL object)

Any ideas?

**Comment by PeterDaveHello** [comment]
@NickiHell have you tried to use a bridge (ref: #34)?

**Comment by NickiHell** [comment]
> @NickiHell have you tried to use a bridge (ref: #34)?

Thanks, with bridges and installing obfsproxy works fine.

**Comment by NickiHell** [comment]
> @NickiHell Nice, I think we got a reason to add it by default, so that users in those area that blocking Tor can connect to the onion network a little bit easier.

It would be cool, it remains to figure out how to pull bridges and from where (the site with tor bridges is not usually available in countries where there are connection problems) during the container assembly :)

**Comment by PeterDaveHello** [comment]
@NickiHell I think I'll leave the bridge lists to the users, didn't plan to frequently update the image just for the bridges.
