### ISSUE TITLE
你好，想要联系到你

### ISSUE THREAD

**Issue by ronnyzhao** [PeterDaveHello/tor-socks-proxy#6]
你好，想问你点问题，我的邮箱zybroseman2010@126.com
你看到了，希望给我回复
是关于volumio项目中的问题，谢谢

**Comment by ronnyzhao** [comment]
你好，我叫赵艳彪，我想问一下volumio项目问题
volumio OEM需要多少费用
还有我如果对volumio 二次开发会侵权吗？

在 2018-08-23 15:57:07，"Peter Dave Hello" <notifications@github.com> 写道：


Closed #6.

**Comment by PeterDaveHello** [comment]
@ronnyzhao ask its author please ...

**Comment by ronnyzhao** [comment]
哦
