### ISSUE TITLE
Log pass

### ISSUE THREAD

**Issue by Azat868** [PeterDaveHello/tor-socks-proxy#9]
Is it possible to set a password for a proxy?

**Comment by PeterDaveHello** [comment]
As this project is not designed for sharing usage, a password isn't supported currently, and even if we want to support authentication, we'll need another proxy to implement it as it's not supported by tor natively, either.

> **SocksPort [address:]port|unix:path|auto [flags] [isolation flags]**
>
>    Open this port to listen for connections from SOCKS-speaking applications. Set this to 0 if you don’t want to allow application connections via SOCKS. Set it to "auto" to have Tor pick a port for you. This directive can be specified multiple times to bind to multiple addresses/ports. If a unix domain socket is used, you may quote the path using standard C escape sequences. (Default: 9050)
>
>    NOTE: Although this option allows you to specify an IP address other than localhost, you should do so only with extreme caution. The SOCKS protocol is unencrypted and (as we use it) **unauthenticated**, so exposing it in this way could leak your information to anybody watching your network, and allow anybody to use your computer as an open proxy.
>
>    The isolation flags arguments give Tor rules for which streams received on this SocksPort are allowed to share circuits with one another. Recognized isolation flags are: 
https://www.torproject.org/docs/tor-manual.html

I prefer not to do that yet :)
